# Generated by Django 3.0 on 2020-09-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mayorista',
            field=models.BooleanField(default=False),
        ),
    ]
